# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the rest of the USB drivers
# (the ones that don't fit into any other categories)
#
obj-$(CONFIG_SEC_USB_LINKLAYER_TEST)	+= sec_lvstest.o

subdir-ccflags-y += -I${ROOT_DIR}/${KERNEL_DIR}/drivers/usb/misc
