# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022 Samsung Electronics Inc.

$(info start build of adaptive_mipi)

# Build common adaptive mipi files
ADAPTIVE_MIPI_OBJS += ../common/adaptive_mipi/imgsensor_adaptive_mipi.o

$(info ADAPTIVE_MIPI_OBJS : $(ADAPTIVE_MIPI_OBJS))
$(info build of adaptive_mipi completed)
