obj-$(CONFIG_UH) 		+= uh_debug_log.o
obj-$(CONFIG_RKP)                 += rkp.o
obj-$(CONFIG_RKP)                 += rkp_module_support.o
obj-$(CONFIG_KDP)                 += kdp.o
ccflags-y := -Wformat
